name: "🏗️ Build mod"
run-name: >
  build ${{github.repository}} #${{ github.run_number }}

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: jcdcdev.Eco.Signs
      PROJECT_PATH: ./src/jcdcdev.Eco.Signs/jcdcdev.Eco.Signs.csproj
      BUILD_OUTPUT: ./build-output
      MOD_OUTPUT: ./build-assets/Mods/jcdcdev.Eco.Signs
      ASSET_NAME: jcdcdev.Eco.Signs-dev-${{ github.sha }}
      ARTIFACT_OUTPUT: ./build-assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download, Extract, and Copy DLLs
        shell: pwsh
        run: |
          Push-Location ./src
          pwsh ./download-dependencies.ps1 -WorkingDir "./src"
          Pop-Location
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -o ${{ env.MOD_OUTPUT }} --configuration Release
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.ARTIFACT_OUTPUT }}
          dest: ${{ env.ASSET_NAME }}.zip
      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET_NAME }}.zip
