name: "🚀 Release mod"
run-name: >
  release ${{github.repository}} #${{ github.run_number }}

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  determine-version:
    name: determine version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.5.0
        with:
          versionSpec: "6.7.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.5.0
  build:
    name: build ${{ needs.determine-version.outputs.semVer }}
    runs-on: ubuntu-latest
    needs:
      - determine-version
    env:
      SEMVER: ${{ needs.determine-version.outputs.semVer }}
      ASSET_NAME: jcdcdev.Eco.Signs-${{ needs.determine-version.outputs.semVer }}
      PROJECT_NAME: jcdcdev.Eco.Signs
      PROJECT_PATH: ./src/jcdcdev.Eco.Signs/jcdcdev.Eco.Signs.csproj
      MOD_OUTPUT: ./build-assets/Mods/jcdcdev.Eco.Signs
      ARTIFACT_OUTPUT: ./build-assets
    outputs:
      assetName: ${{ env.ASSET_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download, Extract, and Copy DLLs
        shell: pwsh
        run: |
          Push-Location ./src
          pwsh ./download-dependencies.ps1 -WorkingDir "./src"
          Pop-Location
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -o ${{ env.MOD_OUTPUT }} --configuration Release -p:Version=${{ env.SEMVER }}
      - uses: vimtor/action-zip@v1.3
        with:
          files: ${{ env.ARTIFACT_OUTPUT }}
          dest: ${{ env.ASSET_NAME }}.zip
      - name: Upload mod
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET_NAME }}.zip
  create-release:
    name: create release ${{ needs.determine-version.outputs.semVer }}
    needs:
      - determine-version
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SEMVER: ${{ needs.determine-version.outputs.semVer }}
      ASSET_NAME: ${{ needs.build.outputs.assetName }}
    steps:
      - name: Create Release
        id: create-release
        uses: jcdcdev/jcdcdev.GitHub.CreateRelease@v1.0.18
        with:
          artifact-name: ${{ env.ASSET_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SEMVER }}
          rich-format: false
      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ASSET_NAME }}
      - uses: nickelc/upload-to-modio@v3.0.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: ${{ secrets.MODIO_GAME }}
          mod: ${{ secrets.MODIO_MOD }}
          version: ${{ env.SEMVER }}
          path: ${{ env.ASSET_NAME }}.zip
          active: true
          changelog: ${{ steps.create-release.outputs.changelog }}
  sync-readme:
    needs:
      - create-release
    uses: ./.github/workflows/sync-readme.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
