name: Sync modio mod assets
on:
  workflow_dispatch:
  workflow_call:
jobs:
  update_mod_description:
    runs-on: ubuntu-latest
    name: "Update modio mod assets"
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Sync modio mod assets
          uses: jcdcdev/jcdcdev.Modio.SyncDocs@main
          with:
            LOGO_PATH: "docs/logo.png"
            IMAGES_PATH: "docs/screenshots"
            README_PATH: ".github/README.md"
            PROJECT_AUTHOR: "JCDC DEV"
            PROJECT_NAME: "SIGNS"
            PROJECT_URL: "${{ github.server_url }}/${{ github.repository }}"
            # Imejis variables
            IMEJIS_DESIGN_ID: "${{ secrets.DESIGN_ID }}"
            IMEJIS_KEY: "${{ secrets.IMEJIS_KEY }}"
            # Mod.io variables
            MODIO_GAME: "${{ secrets.MODIO_GAME }}"
            MODIO_MOD: "${{ secrets.MODIO_MOD }}"
            MODIO_TOKEN: "${{ secrets.MODIO_TOKEN }}"     
            
      