name: 'Sync mod.io README and Images'
on:
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types: [sync-readme]
jobs:
  sync_modio:
    runs-on: ubuntu-latest
    name: 'Sync mod.io README and Images'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync with mod.io
        uses: jcdcdev/jcdcdev.Modio.SyncDocs@main
        with:
          logo-path: "docs/logo.png"
          images-path: "docs/screenshots"
          readme-path: ".github/README.md"
          project-author: "JCDC DEV"
          project-name: "SIGNS"
          imejis-generate-image: true
          imejis-design-id: "${{ secrets.DESIGN_ID }}"
          imejis-key: "${{ secrets.IMEJIS_KEY }}"
          modio-game: "${{ secrets.MODIO_GAME }}"
          modio-mod: "${{ secrets.MODIO_MOD }}"
          modio-token: "${{ secrets.MODIO_TOKEN }}"     
          
      