name: Sync modio mod assets
on:
  workflow_dispatch:
  workflow_call:
jobs:
  update_mod_description:
    runs-on: ubuntu-latest
    name: "Update modio mod assets"
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Sync modio mod assets
          uses: jcdcdev/jcdcdev.Modio.SyncDocs@main
          with:
            logoPath: "docs/logo.png"
            imagesPath: "docs/screenshots"
            readmePath: ".github/README.md"
            projectAuthor: "JCDC DEV"
            projectName: "SIGNS"
            # Imejis variables
            imejisDesignId: "${{ secrets.DESIGN_ID }}"
            imejisKey: "${{ secrets.IMEJIS_KEY }}"
            # Mod.io variables
            modioGame: "${{ secrets.MODIO_GAME }}"
            modioMod: "${{ secrets.MODIO_MOD }}"
            modioToken: "${{ secrets.MODIO_TOKEN }}"     
            
      